num1= int(input("Enter 1st number : "))
num2= int(input("Enter 2nd number : "))
print("Addition is ", num1+num2)
print("Substraction is ", num1-num2)
print("Product is ", num1*num2)
print("Division is ", num1/num2)
print("Modulus is ", num1%num2)
print("Floor division is ", num1//num2)
print("Exponent is ", num1**num2)